apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-sql-state
spec:
  selector:
    matchLabels:
      app: my-sql
  serviceName: my-sql
  replicas: 3
  template:
    metadata:
      labels:
        app: my-sql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
          name: sql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "tarek_123"
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: my-sql-svc
spec:
  selector:
    app: mys-sql
  ports:
  - port: 3306
    targetPort: 3306
  type: NodePort
